# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target 'JKImageCutter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JKImageCutter
  pod 'JKImageCutter','~> 1.0.1'


end
